#!/bin/bash
# Generate version_gen.h from git state and manual major.minor.
# Called by CMake at every build. Only overwrites the output file
# if content has changed (avoids unnecessary recompilation).
#
# Usage: gen_version.sh <major> <minor> <output_file>

set -e

MAJOR="${1:?Usage: gen_version.sh <major> <minor> <output_file>}"
MINOR="${2:?}"
OUTPUT="${3:?}"

# Git info (run from repo root via WORKING_DIRECTORY in CMake)
BUILD=$(git rev-list --count HEAD 2>/dev/null || echo 0)
HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
if git diff --quiet HEAD 2>/dev/null; then
    DIRTY=0
    DIRTY_SUFFIX=""
else
    DIRTY=1
    DIRTY_SUFFIX="+dirty"
fi

VERSION_STRING="${MAJOR}.${MINOR}.${BUILD}+${HASH}${DIRTY_SUFFIX}"

# Build the header content
CONTENT=$(cat <<EOF
/* Auto-generated by gen_version.sh — do not edit */
#ifndef VERSION_GEN_H
#define VERSION_GEN_H

#define FW_VERSION_MAJOR  ${MAJOR}
#define FW_VERSION_MINOR  ${MINOR}
#define FW_VERSION_BUILD  ${BUILD}
#define FW_VERSION_HASH   "${HASH}"
#define FW_VERSION_DIRTY  ${DIRTY}
#define FW_VERSION_STRING "${VERSION_STRING}"

#endif /* VERSION_GEN_H */
EOF
)

# Only write if changed (avoid triggering recompilation when nothing changed)
if [ -f "$OUTPUT" ] && [ "$(cat "$OUTPUT")" = "$CONTENT" ]; then
    exit 0
fi

echo "$CONTENT" > "$OUTPUT"
